// Generated by lsc from compaction.ts

datatype Option<T> = None | Some(value: T)

datatype AgentMessage = AgentMessage(role: string)

method findValidCutPoints(messages: seq<AgentMessage>, start: int, end: int) returns (res: seq<int>)
  requires (0 <= start)
  requires (start <= end)
  requires (end <= |messages|)
  ensures forall k: nat :: ((k < |res|) ==> ((start <= res[k]) && (res[k] < end)))
  ensures forall k: nat :: ((k < |res|) ==> ((messages[res[k]].role == "user") || (messages[res[k]].role == "assistant")))
{
  var cutPoints: seq<int> := [];
  var i := start;
  while (i < end)
    invariant (start <= i)
    invariant (i <= end)
    invariant forall k: nat :: ((k < |cutPoints|) ==> ((start <= cutPoints[k]) && (cutPoints[k] < i)))
    invariant forall k: nat :: ((k < |cutPoints|) ==> ((messages[cutPoints[k]].role == "user") || (messages[cutPoints[k]].role == "assistant")))
    decreases (end - i)
  {
    var role := (if ((0 <= i) && (i < |messages|)) then Option.Some(messages[i].role) else Option.None);
    if ((match role { case Some(i_value) => (i_value == "user") case None => false }) || (match role { case Some(i_value) => (i_value == "assistant") case None => false })) {
      cutPoints := (cutPoints + [i]);
    }
    i := (i + 1);
  }
  return cutPoints;
}
