// Generated by lsc from conversation-reducer.ts

datatype ToolCall = ToolCall(id: string, name: string)

datatype ToolResultMessage = ToolResultMessage(toolCallId: string, toolName: string)

method isCompleteToolBatch(toolCalls: seq<ToolCall>, results: seq<ToolResultMessage>) returns (res: bool)
  ensures (res ==> (|toolCalls| == |results|))
  ensures (res ==> forall k: nat :: ((k < |toolCalls|) ==> ((results[k].toolCallId == toolCalls[k].id) && (results[k].toolName == toolCalls[k].name))))
  ensures (res ==> forall a: nat, b: nat :: ((a < b) ==> (b < |toolCalls|) ==> (toolCalls[a].id != toolCalls[b].id)))
{
  if (|toolCalls| != |results|) {
    return false;
  }
  var seen: set<string> := {};
  var index := 0;
  while (index < |toolCalls|)
    invariant (index <= |toolCalls|)
    invariant (|toolCalls| == |results|)
    invariant forall k: nat :: ((k < index) ==> ((results[k].toolCallId == toolCalls[k].id) && (results[k].toolName == toolCalls[k].name)))
    invariant forall k: nat :: ((k < index) ==> (toolCalls[k].id in seen))
    invariant forall a: nat, b: nat :: ((a < b) ==> (b < index) ==> (toolCalls[a].id != toolCalls[b].id))
    decreases (|toolCalls| - index)
  {
    var call := toolCalls[index];
    var result := results[index];
    if ((false || false) || (call.id in seen)) {
      return false;
    }
    seen := (seen + {call.id});
    if ((result.toolCallId != call.id) || (result.toolName != call.name)) {
      return false;
    }
    index := (index + 1);
  }
  return true;
}
