// Generated by lsc from session-identity.ts

function isTaskSessionName(name: string): bool
{
  (|name| >= |TASK_SESSION_PREFIX| && name[..|TASK_SESSION_PREFIX|] == TASK_SESSION_PREFIX)
}

lemma isTaskSessionName_ensures(name: string)
  ensures (isTaskSessionName(name) == (|name| >= |TASK_SESSION_PREFIX| && name[..|TASK_SESSION_PREFIX|] == TASK_SESSION_PREFIX))
{
}

function isActionScopeName(name: string): bool
{
  (|name| >= |ACTION_SCOPE_PREFIX| && name[..|ACTION_SCOPE_PREFIX|] == ACTION_SCOPE_PREFIX)
}

lemma isActionScopeName_ensures(name: string)
  ensures (isActionScopeName(name) == (|name| >= |ACTION_SCOPE_PREFIX| && name[..|ACTION_SCOPE_PREFIX|] == ACTION_SCOPE_PREFIX))
{
}

function isPublicSessionName(name: string): bool
{
  (!(isTaskSessionName(name)) && !(isActionScopeName(name)))
}

lemma isPublicSessionName_ensures(name: string)
  ensures (isPublicSessionName(name) == (!((|name| >= |TASK_SESSION_PREFIX| && name[..|TASK_SESSION_PREFIX|] == TASK_SESSION_PREFIX)) && !((|name| >= |ACTION_SCOPE_PREFIX| && name[..|ACTION_SCOPE_PREFIX|] == ACTION_SCOPE_PREFIX))))
{
}

function createTaskSessionName(parentSession: string, taskId: string): string
{
  (((("" + TASK_SESSION_PREFIX) + parentSession) + ":") + taskId)
}

lemma createTaskSessionName_ensures(parentSession: string, taskId: string)
  ensures !(isPublicSessionName(createTaskSessionName(parentSession, taskId)))
{
}

function createActionScopeName(invocationId: string): string
{
  (("" + ACTION_SCOPE_PREFIX) + invocationId)
}

lemma createActionScopeName_ensures(invocationId: string)
  ensures !(isPublicSessionName(createActionScopeName(invocationId)))
{
}

const TASK_SESSION_PREFIX: string := "task:"

const ACTION_SCOPE_PREFIX: string := "action:"
