// Generated by lsc from submission-state.ts

datatype Option<T> = None | Some(value: T)

function {:axiom} isRetryableModelError(message: AssistantMessage): bool

datatype AgentMessage = AgentMessage(role: string)

type AssistantMessage = AgentMessage

datatype CanonicalSubmissionEntry = message(id: string, message: AgentMessage) | compaction(id: string)

method countConsecutiveRetryableModelErrors(entries: seq<CanonicalSubmissionEntry>) returns (res: int)
  ensures (0 <= res)
  ensures (res <= |entries|)
{
  var count := 0;
  var i := (|entries| - 1);
  while (i >= 0)
    invariant (0 <= count)
    invariant (count <= ((|entries| - 1) - i))
    invariant (count <= |entries|)
    decreases (i + 1)
  {
    var entry := (if ((0 <= i) && (i < |entries|)) then Option.Some(entries[i]) else Option.None);
    match entry {
      case Some(i_entry_val) =>
        match i_entry_val {
          case message(i__entry_val_id, i__entry_val_message) =>
            if (i__entry_val_message.role == "user") {
              return count;
            }
            if (i__entry_val_message.role != "assistant") {
              i := (i - 1);
              continue;
            }
            if !(isRetryableModelError(i__entry_val_message)) {
              return count;
            }
            count := (count + 1);
            i := (i - 1);
          case compaction(i__entry_val_id) =>
            i := (i - 1);
            continue;
        }
      case None =>
        i := (i - 1);
    }
  }
  return count;
}
