// Generated by lsc from usage.ts

datatype PromptUsageCost = PromptUsageCost(input: int, output: int, cacheRead: int, cacheWrite: int, total: int)

datatype PromptUsage = PromptUsage(input: int, output: int, cacheRead: int, cacheWrite: int, totalTokens: int, cost: PromptUsageCost)

function emptyUsage(): PromptUsage
{
  PromptUsage(0, 0, 0, 0, 0, PromptUsageCost(0, 0, 0, 0, 0))
}

function addUsage(a: PromptUsage, b: PromptUsage): PromptUsage
{
  PromptUsage((a.input + b.input), (a.output + b.output), (a.cacheRead + b.cacheRead), (a.cacheWrite + b.cacheWrite), (a.totalTokens + b.totalTokens), PromptUsageCost((a.cost.input + b.cost.input), (a.cost.output + b.cost.output), (a.cost.cacheRead + b.cost.cacheRead), (a.cost.cacheWrite + b.cost.cacheWrite), (a.cost.total + b.cost.total)))
}

method i_usageIdentity(u: PromptUsage)
  ensures (addUsage(u, emptyUsage()) == u)
  ensures (addUsage(emptyUsage(), u) == u)
{

}

method i_usageCommutes(a: PromptUsage, b: PromptUsage)
  ensures (addUsage(a, b) == addUsage(b, a))
{

}

method i_usageAssociates(a: PromptUsage, b: PromptUsage, c: PromptUsage)
  ensures (addUsage(addUsage(a, b), c) == addUsage(a, addUsage(b, c)))
{

}
